/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCBPDF
#define ROOCBPDF
#include "RooFit.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooCBPdf : public RooAbsPdf {
public:
  RooCBPdf() {} ; 
  RooCBPdf(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha1,
	      RooAbsReal& _alpha2,
	      RooAbsReal& _n1,
	      RooAbsReal& _n2);
  RooCBPdf(const RooCBPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCBPdf(*this,newname); }
  inline virtual ~RooCBPdf() { }

protected:

  RooRealProxy m ;
  RooRealProxy  m0 ;
  RooRealProxy  sigma ;
  RooRealProxy  alpha1 ;
  RooRealProxy  alpha2 ;
  RooRealProxy  n1 ;
  RooRealProxy  n2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCBPdf,1) // Your description goes here...
};
 
#endif
