#!/bin/bash


#gen RooKey fit Expol
hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m150_cat0.root TestSWResults/biasCheck_gRooKey_fExpol_m150_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m150_cat1.root TestSWResults/biasCheck_gRooKey_fExpol_m150_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m150_cat2.root TestSWResults/biasCheck_gRooKey_fExpol_m150_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m150_cat3.root TestSWResults/biasCheck_gRooKey_fExpol_m150_cat3_j*.root
 
hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m200_cat0.root TestSWResults/biasCheck_gRooKey_fExpol_m200_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m200_cat1.root TestSWResults/biasCheck_gRooKey_fExpol_m200_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m200_cat2.root TestSWResults/biasCheck_gRooKey_fExpol_m200_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m200_cat3.root TestSWResults/biasCheck_gRooKey_fExpol_m200_cat3_j*.root
 
hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m250_cat0.root TestSWResults/biasCheck_gRooKey_fExpol_m250_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m250_cat1.root TestSWResults/biasCheck_gRooKey_fExpol_m250_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m250_cat2.root TestSWResults/biasCheck_gRooKey_fExpol_m250_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m250_cat3.root TestSWResults/biasCheck_gRooKey_fExpol_m250_cat3_j*.root
 
hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m300_cat0.root TestSWResults/biasCheck_gRooKey_fExpol_m300_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m300_cat1.root TestSWResults/biasCheck_gRooKey_fExpol_m300_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m300_cat2.root TestSWResults/biasCheck_gRooKey_fExpol_m300_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m300_cat3.root TestSWResults/biasCheck_gRooKey_fExpol_m300_cat3_j*.root
 
hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m400_cat0.root TestSWResults/biasCheck_gRooKey_fExpol_m400_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m400_cat1.root TestSWResults/biasCheck_gRooKey_fExpol_m400_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m400_cat2.root TestSWResults/biasCheck_gRooKey_fExpol_m400_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fExpol_m400_cat3.root TestSWResults/biasCheck_gRooKey_fExpol_m400_cat3_j*.root

#gen RooKey fit DiJet
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m150_cat0.root TestSWResults/biasCheck_gRooKey_fDiJet_m150_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m150_cat1.root TestSWResults/biasCheck_gRooKey_fDiJet_m150_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m150_cat2.root TestSWResults/biasCheck_gRooKey_fDiJet_m150_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m150_cat3.root TestSWResults/biasCheck_gRooKey_fDiJet_m150_cat3_j*.root
 
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m200_cat0.root TestSWResults/biasCheck_gRooKey_fDiJet_m200_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m200_cat1.root TestSWResults/biasCheck_gRooKey_fDiJet_m200_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m200_cat2.root TestSWResults/biasCheck_gRooKey_fDiJet_m200_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m200_cat3.root TestSWResults/biasCheck_gRooKey_fDiJet_m200_cat3_j*.root
 
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m250_cat0.root TestSWResults/biasCheck_gRooKey_fDiJet_m250_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m250_cat1.root TestSWResults/biasCheck_gRooKey_fDiJet_m250_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m250_cat2.root TestSWResults/biasCheck_gRooKey_fDiJet_m250_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m250_cat3.root TestSWResults/biasCheck_gRooKey_fDiJet_m250_cat3_j*.root
 
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m300_cat0.root TestSWResults/biasCheck_gRooKey_fDiJet_m300_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m300_cat1.root TestSWResults/biasCheck_gRooKey_fDiJet_m300_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m300_cat2.root TestSWResults/biasCheck_gRooKey_fDiJet_m300_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m300_cat3.root TestSWResults/biasCheck_gRooKey_fDiJet_m300_cat3_j*.root
 
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m400_cat0.root TestSWResults/biasCheck_gRooKey_fDiJet_m400_cat0_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m400_cat1.root TestSWResults/biasCheck_gRooKey_fDiJet_m400_cat1_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m400_cat2.root TestSWResults/biasCheck_gRooKey_fDiJet_m400_cat2_j*.root
#hadd -f TestSWResults/mergeDir/biasCheck_gRooKey_fDiJet_m400_cat3.root TestSWResults/biasCheck_gRooKey_fDiJet_m400_cat3_j*.root

