/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCBCRUJFFPDF
#define ROOCBCRUJFFPDF
#include "RooFit.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooCBCrujffPdf : public RooAbsPdf {
public:
  RooCBCrujffPdf() {} ; 
  RooCBCrujffPdf(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha,
	      RooAbsReal& _alphaCB,
	      RooAbsReal& _nCB);
  RooCBCrujffPdf(const RooCBCrujffPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCBCrujffPdf(*this,newname); }
  inline virtual ~RooCBCrujffPdf() { }

protected:

  RooRealProxy m ;
  RooRealProxy  m0 ;
  RooRealProxy  sigma ;
  RooRealProxy  alpha ;
  RooRealProxy  alphaCB ;
  RooRealProxy  nCB ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCBCrujffPdf,1) // Your description goes here...
};
 
#endif
